apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: elasticai-kubewatch-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: elasticai-kubewatch
  minReplicas: 1
  maxReplicas: 10  # Adjust as needed based on your requirements
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60  # Adjust the target utilization percentage as needed
    - type: Resource
      resource:
        name: memory
        targetAverageValue: 500Mi  # Adjust the target average memory value as needed
